# Generated by Django 5.1.6 on 2025-03-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0038_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Cancelled", "Cancelled"),
                    ("New", "New"),
                    ("Completed", "Completed"),
                ],
                default="New",
                max_length=10,
            ),
        ),
    ]
